<!doctype html><html lang="zh-tw">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="throw 用來拋出例外，在捕捉到錯誤時，若要重新拋出錯誤，也是使用 throw；視需求而定，若捕捉錯誤後，當時情境沒有足夠的資訊可以妥善處理，可就現有資訊處理完錯誤後，重新拋出原錯誤，或者是收集資訊...">

    <meta property="og:locale" content="zh_TW">
    <meta property="og:title" content="拋出例外">
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://openhome.cc/Gossip/CppGossip/Throw.html">
    <meta property="og:image" content="https://openhome.cc/Gossip/images/caterpillar_small.jpg">
    <meta property="og:site_name" content="OPENHOME.CC">
    <meta property="og:description" content="throw 用來拋出例外，在捕捉到錯誤時，若要重新拋出錯誤，也是使用 throw；視需求而定，若捕捉錯誤後，當時情境沒有足夠的資訊可以妥善處理，可就現有資訊處理完錯誤後，重新拋出原錯誤，或者是收集資訊...">

    <title>拋出例外</title>

    <link rel="stylesheet" href="../css/pure-0.6.0/pure-min.css">

    <!--[if lte IE 8]>
        <link rel="stylesheet" href="../css/layouts/side-menu-old-ie.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="../css/layouts/side-menu.css">
    <!--<![endif]-->
  

     <link rel="stylesheet" href="../css/caterpillar.css">
     <script async src="../google-code-prettify/run_prettify.js"></script>
     <!-- 網頁層級廣告 --><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><script>(adsbygoogle =window.adsbygoogle || []).push({google_ad_client: "ca-pub-9750319131714390",enable_page_level_ads: true });</script></head>
<body>

<div id="layout">
    <!-- Menu toggle -->
    <a href="Throw.html#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
    </a>
    <div id="menu">
        <div class="pure-menu">
            <a class="pure-menu-heading" href="index.html">回 C++ 目錄</a>
            <ul class="pure-menu-list">
                <li class="pure-menu-item"><br><div class="social" style="text-align: center;"><a href="http://twitter.com/caterpillar"><img title="Twitter" alt="Twitter" src="../images/twitter.png"></a> <a href="http://www.facebook.com/openhome.cc"><img title="Facebook" alt="Facebook" src="../images/facebook.png"></a></div><br> <div id="search box"><script>(function() {var cx = 'partner-pub-9750319131714390:3926766884';var gcse = document.createElement('script');gcse.type = 'text/javascript';gcse.async = true;gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//www.google.com/cse/cse.js?cx=' + cx;var s = document.getElementsByTagName('script')[0];s.parentNode.insertBefore(gcse, s);})();</script><gcse:searchbox-only></gcse:searchbox-only></div><br><div class="ad" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- 2015 新版型 160 x 600 廣告 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:160px;height:600px"
     data-ad-client="ca-pub-9750319131714390"
     data-ad-slot="3747048883"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script></div></li>
            </ul>
        </div>
    </div>

    <main id="main">
        <header class="header">
            <h1>拋出例外</h1>
        </header>

        <article class="content">
            <br><div class="ad-3" style="text-align: center;"><script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型回應式廣告 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="7104125683" data-ad-format="auto"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div> 
            
            <p><code>throw</code> 用來拋出例外，在捕捉到錯誤時，若要重新拋出錯誤，也是使用 <code>throw</code>；視需求而定，若捕捉錯誤後，當時情境沒有足夠的資訊可以妥善處理，可就現有資訊處理完錯誤後，重新拋出原錯誤，或者是收集資訊後建立新的錯誤拋出。</p>
<p>例如，如果你想將 <code>invalid_argument</code> 也視為一種無法修正的錯誤，可以在捕捉、進行日誌後重新拋出：</p>
<pre class="prettyprint"><code lang="c++">try {
    acct.withdraw(10200);
    acct.deposit(-500);
}
catch(invalid_argument &amp;ex) {
    cout &lt;&lt; "引數錯誤：" &lt;&lt; ex.what() &lt;&lt; endl;
    throw;
}
catch(Insufficient &amp;ex) {
    cout &lt;&lt; "帳號錯誤："  &lt;&lt; endl
         &lt;&lt; "\t" &lt;&lt; ex.what() &lt;&lt; endl
         &lt;&lt; "\t餘額 " &lt;&lt; ex.getBalance() &lt;&lt; endl;
}
</code></pre>
<p>或者是更具體一些，抽取 <code>invalid_argument</code> 訊息，重新建立 <code>runtime_error</code> 後拋出：</p>
<pre class="prettyprint"><code lang="c++">try {
    acct.withdraw(10200);
    acct.deposit(-500);
}
catch(invalid_argument &amp;ex) {
    cout &lt;&lt; "引數錯誤：" &lt;&lt; ex.what() &lt;&lt; endl;
    throw runtime_error(ex.what());
}
catch(Insufficient &amp;ex) {
    cout &lt;&lt; "帳號錯誤："  &lt;&lt; endl
         &lt;&lt; "\t" &lt;&lt; ex.what() &lt;&lt; endl
         &lt;&lt; "\t餘額 " &lt;&lt; ex.getBalance() &lt;&lt; endl;
}
</code></pre>
<p>如果函式或方法確認不會拋出例外，可以使用 <code>noexcept</code> 指明，例如：</p>
<pre class="prettyprint"><code lang="c++">void foo() noexcept {
    ...
}
</code></pre>
<p>知道一個函式或方法不會拋出例外，就不用費心去準備 <code>try-catch</code>，如果 <code>foo</code> 函式程式碼中不經意撰寫了 <code>throw</code> 試圖拋出例外，編譯器會提出警訊，不過編譯還是會通過，執行時期若真的拋出了例外，那麼程式會直接中斷，是否會有例外的傳播、<code>try-catch</code> 等行為都是不可確定的。</p>
<p><code>noexcept</code> 可以接受運算式，例如 <code>noexcept(expr)</code>，如果 <code>expr</code> 結果是 <code>true</code>，表示該函式不會拋出例外，若為 <code>false</code>，該函式不應拋出例外。</p>
<p>C++ 有個 <code>catch(...)</code> 語言，並不建議使用，它可以用來捕捉全部類型的例外，捕捉之目的通常是為了留下日誌並重新拋出。例如：</p>
<pre class="prettyprint"><code lang="c++">try {
    foo();
}
catch(SomeException &amp;e) {
    ...
}
catch(...) {
    cout &lt;&lt; "foo 呼叫發生未處理的錯誤" &lt;&lt; endl;
    throw;
}
</code></pre>
<p>或者設置一個處理各種類型錯誤的函式：</p>
<pre class="prettyprint"><code lang="c++">#include &lt;stdexcept&gt;
#include &lt;iostream&gt;
#include &lt;string&gt;
using namespace std;

void what(const exception_ptr &amp;eptr = current_exception()) {
    if (!eptr) { 
        throw bad_exception(); 
    }

    try { 
        rethrow_exception(eptr); 
    }
    catch (const std::exception &amp;e) { 
        cout &lt;&lt; e.what() &lt;&lt; endl; 
    }
    catch(const string &amp;e) { 
        cout &lt;&lt; e &lt;&lt; endl;

    }
    catch (const char *e) { 
        cout &lt;&lt; e &lt;&lt; endl; 
    }
    catch (...) { 
        cout &lt;&lt; "unknow error type" &lt;&lt; endl;
        throw; 
    }
}

int main() {
    try { 
        throw "XD happens!";
    }
    catch (...) { 
        what();  
    }

    try { 
        throw 42; 
    } catch (...) {
        what();
    }
}
</code></pre>
<p><code>current_exception</code> 可以取得目前捕捉到的例外，並以 <code>exception_ptr</code> 型態傳回，如果沒有指向任何例外，那會傳回 <code>nullptr</code>，<code>rethrow_exception</code> 接受 <code>exception_ptr</code> 並重新拋出例外，因此可以在 <code>what</code> 中嘗試進行對應型態的捕捉。</p>

            
           <br><br><div class="ad336-280" style="text-align: center;"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 2015 新版型廣告 336 x 280 --><ins class="adsbygoogle" style="display:inline-block;width:336px;height:280px" data-ad-client="ca-pub-9750319131714390" data-ad-slot="9976409681"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div><br><div class="recommend" style="text-align: center;"><hr><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><!-- 自動大小回應相符內容 --><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-9750319131714390" data-ad-slot="4953478487" data-ad-format="autorelaxed"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});</script></div>
        </article>
    </main>
</div></body>
</html>
<script src="../js/ui.js"></script>
<div class="analytics"><script async src="https://www.googletagmanager.com/gtag/js?id=G-QVQQYFSC8J"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-QVQQYFSC8J');</script></div>
